@startuml

package "Gestión Hotelera Safari’S" {

abstract class Persona {
    - String dni
    - String nombre
    - String direccion
    - String telefono
    --
    + toString()
}

class Empleado {
    - int codigo
    - String nivelEducativo
    - String tipo
    - Hotel hotel
    --
    + asignarHotel(hotel)
    + obtenerInformacion()
    + toString()
}

class Cliente {
    -- 
    + verHistorialReservas()
    + contratarActividad(Actividad)
    + toString()
}

class Hotel {
    - int codigo
    - String nombre
    - int categoria
    - String direccion
    - String telefono
    - Empleado director
    --
    + agregarEmpleado(Empleado)
    + agregarHabitacion(Habitacion)
    + listarEmpleadosTipo(String)
    + getDisponibilidadTipo(String)
    + toString()
}

class Habitacion {
    - int numero
    - String tipo
    - boolean disponible
    - double precioBase
    - List<Suplemento> suplementos
    - Hotel hotel
    --
    + calcularPrecioTotal()
    + agregarSuplemento(suplemento)
    + toString()
}

class Reserva {
    - int id
    - Cliente cliente
    - Hotel hotel
    - List<Habitacion> habitacionesReservadas
    - Date fechaInicio
    - Date fechaFin
    - double anticipo
    - boolean confirmada
    - String estado
    --
    + validarFechas()
    + calcularPrecio()
    + cancelarReserva(String)
    + toString()
}

class Estancia {
    - int id
    - Reserva reserva
    - List <Habitacion> habitacionesOcupadas
    - Date fechaInicio
    - Date fechaFin
    - List<Actividad> actividadesContratadas
    --
    + calcularTotalEstancia()
    + validarCondicionesReserva()
    + toString() 
}

class Actividad {
    - int codigo
    - String nombre
    - String descripcion
    - String horario
    - List<String> diasSemana
    - boolean gratuito
    - double precio
    - Empleado animador
    --
    + calcularCostoCliente()
    + verDetalles()
    + toString()
}

class Suplemento {
    - String tipo
    - double importe
    --
    + sumarAlPrecio(double)
    + toString()
}

class Factura {
    - int id
    - Estancia estancia
    - Date fechaEmision
    - double totalHabitaciones
    - double totalSuplementos
    - double totalActividades
    - double anticipoDescontado
    - double totalPagar
    --
    + calcularTotal()
    + generarFactura()
    + toString()
}

}
@enduml
